<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <?php require __DIR__ . '/modules/styles.phtml' ?>
</head>
<body>
    <?php require __DIR__ . '/modules/header.phtml' ?>
    <h1>About page</h1>
    <?php require __DIR__ . '/modules/scripts.phtml' ?>
</body>
</html>