<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p><?= isset ($context['message']) ? $context['message']: '' ?></p>

    <form action="form" method="POST">
        <input type="text" name="title">
        <button type="submit">Ok</button>
    </form>
</body>
</html>