<header class="header">
    <a href="/" class="header__brand">My app</a>

    <nav class="nav">
        <ul class="nav__list">
            <li class="nav__list__element">
                <a href="#" class="nav__link">Link 1</a>
            </li>
            <li class="nav__list__element">
                <a href="#" class="nav__link">Link 2</a>
            </li>
            <li class="nav__list__element">
                <a href="#" class="nav__link">Link 3</a>
            </li>
        </ul>
    </nav>
</header>